#!/bin/bash
#Input the plaintext
read -p "Plaintext: " plaintext 

#Removes spaces from plaintext
plaintext=$(echo $plaintext|tr -d ' ')

#echo $plaintext

#Separates the plaintext into three distinct lines.
a=$(echo $plaintext | sed -E 's/(.).{0,3}/\1/g')
b=$(echo $plaintext |sed 's/^.//' | sed -E 's/(.).{1,1}/\1/g')
c=$(echo $plaintext |sed 's/^..//' | sed -E 's/(.).{0,3}/\1/g')

echo $a$b$c
